name: PlatformIO CI

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Deploy CI-CD host
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cashe/pip
            ~/.platformio/.cache
          key: ${{runner.os}}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
