name: PlatformIO CI

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy CI-CD host
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Enable caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cashe/pip
            ~/.platformio/.cache
          key: ${{runner.os}}-pio
      - name: Deploy Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Execute tests
        run: |
          declare testcount=0
          declare failedcount=0
          declare ignoredcount=0
          declare projectcount=0
          declare projectfailed=0
          for file in $(find . -name "test" -type f -print); do
            declare folder="$(dirname "$file")"    
            if [[ "$folder" != *".pio"* ]]; then
              echo "$folder"
              pio -h
            fi
          done
    
